image: dart:stable-sdk@sha256:8add685872d0d6e9b841ef85b4c42415ae55a5d32b3d7a9dd51f88605c90cce3

stages:
  - lint
  - test

codespell:
  stage: lint
  image:
    name: $CI_REGISTRY/tools/cspell:latest
  script:
    - cspell .

analyze:
  stage: lint
  script:
    - dart pub get
    - dart analyze # analyzer linting rules
    - dart format . --set-exit-if-changed # dart format
  only:
    refs:
      - merge_requests
    changes:
      - lib/**/*.dart
      - test/**/*.dart

pana:
  stage: lint
  image: ghcr.io/cirruslabs/flutter:stable@sha256:d268f4fdc50c2d7c55d2f6e5823725db0d424dd6b50502fe4ee0533d5c6afe1f
  script:
    - dart pub get
    - dart run pana --exit-code-threshold 0
  only:
    refs:
      - merge_requests
